<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_61235178a7c0d',
	'title' => 'تگ های متا',
	'fields' => array(
		array(
			'key' => 'field_62e40179be3f2',
			'label' => 'سئو',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_635547d6038b3',
			'label' => 'لینک دکمه سفارش',
			'name' => 'link-order',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'https://panel.ariapay.me',
			'placeholder' => '',
		),
		array(
			'key' => 'field_61241bd4f7faf',
			'label' => 'توضيحات کوتاه هدر',
			'name' => 'description_head',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 5,
			'new_lines' => '',
		),
		array(
			'key' => 'field_612352b44ab46',
			'label' => 'تگ تايتل',
			'name' => 'tag_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_612352ea4ab47',
			'label' => 'تگ توضيحات',
			'name' => 'tag_ description',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6123577a0db26',
			'label' => 'تگ های html آزاد',
			'name' => 'tag_html',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_654e965a8bd40',
			'label' => 'سوالات متداول',
			'name' => 'faq-field',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'rows_per_page' => 20,
			'layout' => 'table',
			'button_label' => 'سطر جدید',
			'collapsed' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_654e9714cbea1',
					'label' => 'سوال',
					'name' => 'question-field',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_654e965a8bd40',
				),
				array(
					'key' => 'field_654e9766cbea2',
					'label' => 'پاسخ',
					'name' => 'response-field',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_654e965a8bd40',
				),
			),
		),
		array(
			'key' => 'field_62e402a9507af',
			'label' => 'ویدئو',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_62e14ac5ff30e',
			'label' => 'ویدئو یوتیوپ',
			'name' => 'video_youtube',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '<iframe width="100%" height="350px" loading="lazy" src="https://www.youtube.com/embed/2lGQz4kqDE8?controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62e14b85ff30f',
			'label' => 'ویدئو آپارات',
			'name' => 'video_aparat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '<div id="50782270268"><script type="text/JavaScript" src="https://www.aparat.com/embed/AYGfN?data[rnddiv]=50782270268&data[responsive]=yes"></script></div>',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62e40378f6c36',
			'label' => 'نکات مهم',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_62e403f5ff366',
			'label' => 'متن نکات مهم',
			'name' => 'important-points',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_62e404b0ff368',
			'label' => 'لیست نکات مهم',
			'name' => 'important-list',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_62e40581ff36b',
					'label' => 'آیکن1',
					'name' => 'icon1',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '<i class="icon-clipbord"></i>',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e407681a38b',
					'label' => 'متن آیکن1',
					'name' => 'text-icon1',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'پرداخت آنلاین',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e407541a38a',
					'label' => 'آیکن2',
					'name' => 'icon2',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '<i class="icon-clipbord"></i>',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e407f51a38c',
					'label' => 'متن آیکن2',
					'name' => 'text-icon2',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'پرداخت آنلاین',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e409541f2c3',
					'label' => 'آیکن3',
					'name' => 'icon3',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '<i class="icon-clipbord"></i>',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e409591f2c4',
					'label' => 'متن آیکن3',
					'name' => 'text-icon3',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'پرداخت آنلاین',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e409761f2c5',
					'label' => 'آیکن4',
					'name' => 'icon4',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '<i class="icon-clipbord"></i>',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_62e4097c1f2c6',
					'label' => 'متن آیکن4',
					'name' => 'text-icon4',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'پرداخت آنلاین',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_63fcae90d46b0',
			'label' => 'باکس قیمت ها',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_63fcaed1d46b1',
			'label' => 'کد قیمت ها',
			'name' => 'panel-item',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'text',
			'media_upload' => 0,
			'toolbar' => 'full',
			'delay' => 0,
		),
		array(
			'key' => 'field_63fcb4c5f29e9',
			'label' => 'نمونه کد',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '<section class="mt-20 services-panel">
				<div class="container">
						<div class="row justify-content-center">
								<div class="col-lg-3">
										<div class="services-panel-item position-relative bg-white">
												<img src="/assets/images/panel-01.png" alt="panel">
												<h2> آی پی ثابت یک ساله </h2>
												<div class="price"> 864 هزار تومان </div>
												<ul>
														<li> 360 گیگ ترافیک </li>
														<li> امکان خرید ترافیک اضافه </li>
												</ul>
												<a target="_blank" href="https://panel.ariapay.me/ip-plus" class="btn"> خرید </a>
										</div>
								</div>
						</div>
				</div>
		</section>',
			'new_lines' => 'br',
			'esc_html' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'blog',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'news',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'trainings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'excerpt',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6163efed150cd',
	'title' => 'تنظیمات',
	'fields' => array(
		array(
			'key' => 'field_6163f010ffd5e',
			'label' => 'وضعیت',
			'name' => 'status',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'موجود' => 'موجود',
				'ناموجود' => 'ناموجود',
			),
			'allow_null' => 1,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6163f1316b9fd',
			'label' => 'هزینه',
			'name' => 'price',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6163f18676abc',
			'label' => 'زمان تحویل',
			'name' => 'time',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6163f5db610f6',
			'label' => 'نام انگلیسی',
			'name' => 'english_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-apple-id.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-binance.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-ip-sabet.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-services.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-tradingview.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-virtual-number.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-telegram.php',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );

	acf_add_local_field_group( array(
	'key' => 'group_612415f481f47',
	'title' => 'باکس های هدر',
	'fields' => array(
		array(
			'key' => 'field_612416d21bc63',
			'label' => 'باکس 1',
			'name' => 'box_1',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_612417171bc64',
					'label' => 'عنوان',
					'name' => 'box_title1',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'انجام فوری سفارشات',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_612417271bc65',
					'label' => 'توضیحات',
					'name' => 'box_disc1',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'سفارشات در کمترین زمان ممکن و با بالاترین کیفیت انجام می شود',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => '',
				),
			),
		),
		array(
			'key' => 'field_612417fed2c15',
			'label' => 'باکس 2',
			'name' => 'box_2',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_612417fed2c16',
					'label' => 'عنوان',
					'name' => 'box_title2',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'قیمت مناسب',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_612417fed2c17',
					'label' => 'توضیحات',
					'name' => 'box_disc2',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'قیمت خدمات ما با توجه به کیفیت ارائه خدمات مناسب و منصفانه هست',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => '',
				),
			),
		),
		array(
			'key' => 'field_6124198bb818f',
			'label' => 'باکس 3',
			'name' => 'box_3',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_6124198bb8190',
					'label' => 'عنوان',
					'name' => 'box_title3',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'امنیت بالا',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_6124198bb8191',
					'label' => 'توضیحات',
					'name' => 'box_disc3',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'حساب کاربری با جدیدترین متُد بانکداری و با امنیت بالا برنامه ریزی شده است',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-services.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-apple-id.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-binance.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-ip-sabet.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-tradingview.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-virtual-number.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-telegram.php',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );
} );

add_action( 'init', function() {
	register_taxonomy( 'category-trainings', array(
	0 => 'trainings',
), array(
	'labels' => array(
		'name' => 'آموزش',
		'singular_name' => 'دسته بندی آموزش',
		'menu_name' => 'دسته بندی ها',
		'all_items' => 'All دسته بندی ها',
		'edit_item' => 'Edit دسته بندی آموزش',
		'view_item' => 'View دسته بندی آموزش',
		'update_item' => 'Update دسته بندی آموزش',
		'add_new_item' => 'Add New دسته بندی آموزش',
		'new_item_name' => 'New دسته بندی آموزش Name',
		'parent_item' => 'Parent دسته بندی آموزش',
		'parent_item_colon' => 'Parent دسته بندی آموزش:',
		'search_items' => 'Search دسته بندی ها',
		'not_found' => 'No دسته بندی ها found',
		'no_terms' => 'No دسته بندی ها',
		'filter_by_item' => 'Filter by دسته بندی آموزش',
		'items_list_navigation' => 'دسته بندی ها list navigation',
		'items_list' => 'دسته بندی ها list',
		'back_to_items' => '← Go to دسته بندی ها',
		'item_link' => 'دسته بندی آموزش Link',
		'item_link_description' => 'A link to a دسته بندی آموزش',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_tagcloud' => false,
	'show_admin_column' => true,
	'rewrite' => array(
		'hierarchical' => true,
	),
) );

	register_taxonomy( 'category-news', array(
	0 => 'news',
), array(
	'labels' => array(
		'name' => 'اخبار',
		'singular_name' => 'دسته بندی اخبار',
		'menu_name' => 'دسته بندی اخبار',
		'all_items' => 'All دسته بندی اخبار',
		'edit_item' => 'Edit دسته بندی اخبار',
		'view_item' => 'View دسته بندی اخبار',
		'update_item' => 'Update دسته بندی اخبار',
		'add_new_item' => 'Add New دسته بندی اخبار',
		'new_item_name' => 'New دسته بندی اخبار Name',
		'parent_item' => 'Parent دسته بندی اخبار',
		'parent_item_colon' => 'Parent دسته بندی اخبار:',
		'search_items' => 'Search دسته بندی اخبار',
		'not_found' => 'No دسته بندی اخبار found',
		'no_terms' => 'No دسته بندی اخبار',
		'filter_by_item' => 'Filter by دسته بندی اخبار',
		'items_list_navigation' => 'دسته بندی اخبار list navigation',
		'items_list' => 'دسته بندی اخبار list',
		'back_to_items' => '← Go to دسته بندی اخبار',
		'item_link' => 'دسته بندی اخبار Link',
		'item_link_description' => 'A link to a دسته بندی اخبار',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_tagcloud' => false,
	'show_admin_column' => true,
	'rewrite' => array(
		'hierarchical' => true,
	),
) );

	register_taxonomy( 'category-blog', array(
	0 => 'blog',
), array(
	'labels' => array(
		'name' => 'بلاگ',
		'singular_name' => 'دسته بندی بلاگ',
		'menu_name' => 'دسته بندی ها',
		'all_items' => 'همه دسته بندی ها',
		'edit_item' => 'ویرایش دسته بندی بلاگ',
		'view_item' => 'مشاهده دسته بندی بلاگ',
		'update_item' => 'بروزرسانی دسته بندی بلاگ',
		'add_new_item' => 'افزودن دسته بندی بلاگ',
		'new_item_name' => 'افزودن دسته بندی بلاگ نام',
		'parent_item' => 'Parent بلاگ',
		'parent_item_colon' => 'Parent بلاگ:',
		'search_items' => 'Search دسته بندی ها',
		'not_found' => 'No دسته بندی ها found',
		'no_terms' => 'No دسته بندی ها',
		'filter_by_item' => 'Filter by بلاگ',
		'items_list_navigation' => 'دسته بندی ها list navigation',
		'items_list' => 'دسته بندی ها list',
		'back_to_items' => '← Go to دسته بندی ها',
		'item_link' => 'دسته بندی بلاگ Link',
		'item_link_description' => 'A link to a دسته بندی بلاگ',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
	'show_tagcloud' => false,
	'show_admin_column' => true,
	'rewrite' => array(
		'hierarchical' => true,
	),
) );
} );

add_action( 'init', function() {
	register_post_type( 'trainings', array(
	'labels' => array(
		'name' => 'آموزش',
		'singular_name' => 'آموزش',
		'menu_name' => 'آموزش',
		'all_items' => 'آموزش ها',
		'edit_item' => 'Edit آموزش',
		'view_item' => 'View آموزش',
		'view_items' => 'View آموزش ها',
		'add_new_item' => 'Add New آموزش',
		'new_item' => 'New آموزش',
		'parent_item_colon' => 'Parent آموزش:',
		'search_items' => 'Search آموزش ها',
		'not_found' => 'No آموزش ها found',
		'not_found_in_trash' => 'No آموزش ها found in Trash',
		'archives' => 'آموزش Archives',
		'attributes' => 'آموزش Attributes',
		'insert_into_item' => 'Insert into آموزش',
		'uploaded_to_this_item' => 'Uploaded to this آموزش',
		'filter_items_list' => 'Filter آموزش ها list',
		'filter_by_date' => 'Filter آموزش ها by date',
		'items_list_navigation' => 'آموزش ها list navigation',
		'items_list' => 'آموزش ها list',
		'item_published' => 'آموزش published.',
		'item_published_privately' => 'آموزش published privately.',
		'item_reverted_to_draft' => 'آموزش reverted to draft.',
		'item_scheduled' => 'آموزش scheduled.',
		'item_updated' => 'آموزش updated.',
		'item_link' => 'آموزش Link',
		'item_link_description' => 'A link to a آموزش.',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-welcome-learn-more',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
	),
	'taxonomies' => array(
		0 => 'category-trainings',
	),
	'has_archive' => 'trainings',
	'rewrite' => array(
		'feeds' => false,
	),
	'delete_with_user' => false,
) );

	register_post_type( 'news', array(
	'labels' => array(
		'name' => 'اخبار',
		'singular_name' => 'خبر',
		'menu_name' => 'خبر',
		'all_items' => 'اخبار',
		'edit_item' => 'Edit خبر',
		'view_item' => 'View خبر',
		'view_items' => 'View اخبار',
		'add_new_item' => 'Add New خبر',
		'new_item' => 'New خبر',
		'parent_item_colon' => 'Parent خبر:',
		'search_items' => 'Search اخبار',
		'not_found' => 'No اخبار found',
		'not_found_in_trash' => 'No اخبار found in Trash',
		'archives' => 'خبر Archives',
		'attributes' => 'خبر Attributes',
		'insert_into_item' => 'Insert into خبر',
		'uploaded_to_this_item' => 'Uploaded to this خبر',
		'filter_items_list' => 'Filter اخبار list',
		'filter_by_date' => 'Filter اخبار by date',
		'items_list_navigation' => 'اخبار list navigation',
		'items_list' => 'اخبار list',
		'item_published' => 'خبر published.',
		'item_published_privately' => 'خبر published privately.',
		'item_reverted_to_draft' => 'خبر reverted to draft.',
		'item_scheduled' => 'خبر scheduled.',
		'item_updated' => 'خبر updated.',
		'item_link' => 'خبر Link',
		'item_link_description' => 'A link to a خبر.',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-site',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
	),
	'taxonomies' => array(
		0 => 'category-news',
	),
	'has_archive' => 'news',
	'rewrite' => array(
		'feeds' => false,
	),
	'delete_with_user' => false,
) );

	register_post_type( 'blog', array(
	'labels' => array(
		'name' => 'بلاگ',
		'singular_name' => 'بلاگ',
		'menu_name' => 'بلاگ',
		'all_items' => 'بلاگ ها',
		'edit_item' => 'Edit بلاگ',
		'view_item' => 'View بلاگ',
		'view_items' => 'View بلاگ ها',
		'add_new_item' => 'Add New بلاگ',
		'new_item' => 'New بلاگ',
		'parent_item_colon' => 'Parent بلاگ:',
		'search_items' => 'Search بلاگ ها',
		'not_found' => 'No بلاگ ها found',
		'not_found_in_trash' => 'No بلاگ ها found in Trash',
		'archives' => 'بلاگ Archives',
		'attributes' => 'بلاگ Attributes',
		'insert_into_item' => 'Insert into بلاگ',
		'uploaded_to_this_item' => 'Uploaded to this بلاگ',
		'filter_items_list' => 'Filter بلاگ ها list',
		'filter_by_date' => 'Filter بلاگ ها by date',
		'items_list_navigation' => 'بلاگ ها list navigation',
		'items_list' => 'بلاگ ها list',
		'item_published' => 'بلاگ published.',
		'item_published_privately' => 'بلاگ published privately.',
		'item_reverted_to_draft' => 'بلاگ reverted to draft.',
		'item_scheduled' => 'بلاگ scheduled.',
		'item_updated' => 'بلاگ updated.',
		'item_link' => 'بلاگ Link',
		'item_link_description' => 'A link to a بلاگ.',
	),
	'public' => true,
	'hierarchical' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-welcome-widgets-menus',
	'supports' => array(
		0 => 'title',
		1 => 'comments',
		2 => 'editor',
		3 => 'thumbnail',
	),
	'taxonomies' => array(
		0 => 'category-blog',
	),
	'has_archive' => 'blog',
	'delete_with_user' => false,
) );
} );


